/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/faroshq/plugin-process/pkg/apis/services/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSystemds implements SystemdInterface
type FakeSystemds struct {
	Fake *FakeServicesV1alpha1
	ns   string
}

var systemdsResource = schema.GroupVersionResource{Group: "services.plugins.faros.sh", Version: "v1alpha1", Resource: "systemds"}

var systemdsKind = schema.GroupVersionKind{Group: "services.plugins.faros.sh", Version: "v1alpha1", Kind: "Systemd"}

// Get takes name of the systemd, and returns the corresponding systemd object, and an error if there is any.
func (c *FakeSystemds) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Systemd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(systemdsResource, c.ns, name), &v1alpha1.Systemd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Systemd), err
}

// List takes label and field selectors, and returns the list of Systemds that match those selectors.
func (c *FakeSystemds) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SystemdList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(systemdsResource, systemdsKind, c.ns, opts), &v1alpha1.SystemdList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SystemdList{ListMeta: obj.(*v1alpha1.SystemdList).ListMeta}
	for _, item := range obj.(*v1alpha1.SystemdList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested systemds.
func (c *FakeSystemds) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(systemdsResource, c.ns, opts))

}

// Create takes the representation of a systemd and creates it.  Returns the server's representation of the systemd, and an error, if there is any.
func (c *FakeSystemds) Create(ctx context.Context, systemd *v1alpha1.Systemd, opts v1.CreateOptions) (result *v1alpha1.Systemd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(systemdsResource, c.ns, systemd), &v1alpha1.Systemd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Systemd), err
}

// Update takes the representation of a systemd and updates it. Returns the server's representation of the systemd, and an error, if there is any.
func (c *FakeSystemds) Update(ctx context.Context, systemd *v1alpha1.Systemd, opts v1.UpdateOptions) (result *v1alpha1.Systemd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(systemdsResource, c.ns, systemd), &v1alpha1.Systemd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Systemd), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSystemds) UpdateStatus(ctx context.Context, systemd *v1alpha1.Systemd, opts v1.UpdateOptions) (*v1alpha1.Systemd, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(systemdsResource, "status", c.ns, systemd), &v1alpha1.Systemd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Systemd), err
}

// Delete takes name of the systemd and deletes it. Returns an error if one occurs.
func (c *FakeSystemds) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(systemdsResource, c.ns, name, opts), &v1alpha1.Systemd{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSystemds) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(systemdsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SystemdList{})
	return err
}

// Patch applies the patch and returns the patched systemd.
func (c *FakeSystemds) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Systemd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(systemdsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Systemd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Systemd), err
}
